pages:
  image: node:18
  script:
    - npm install
    - npm run build
    - mkdir public
    - cp -r dist/* public/
  artifacts:
    paths:
      - public
  only:
    - main  # or 'master' if you're using that branch
